examples/slic/dev-scratch.cfg, examples/slic/dev-versions.py, examples/slic/release-scratch.cfg, examples/slic/release-versions.py
- Fix SLIC configurations after github migration
This should resolve issue #7.
=> Fix SLIC build

builds/release-ilcsoft.cfg, releases/HEAD/release-ilcsoft.cfg, releases/v01-19/release-ilcsoft.cfg
- Change location from where physsim is downloaded in build and release configuration
=> Move physsim to github

builds/release-ilcsoft.cfg, releases/HEAD/release-ilcsoft.cfg, releases/v01-19/release-ilcsoft.cfg
@gaede Please accept the pull "https://github.com/AIDASoft/aidaTT/pull/12" first, then remove this flag from iLCInstall by this pull.
- Apply the flag "-DGBL_EIGEN_SUPPORT_ROOT" in aidaTT "CMakeLists.txt".
=> reorganised this flag, and put it into the aidaTT CMakeLists.txt.

releases/v01-19/release-versions.py
- update pre-release versions vor v01-19-02
=>  update pre-release versions

doc/release_notes_ilcsoft_v01-19-02.txt, releases/v01-19/release-ilcsoft.cfg, releases/v01-19/release-versions.py, releases/v01-19/tagging_v01-19.py, scripts/create_ilcsoft_relnotes.py
- finalized v01-19-02
- added release notes
- added script: create_ilcsoft_relnotes.py
=> prepare v01-19-02

ilcsoft/cernlib.py, ilcsoft/gsl.py, ilcsoft/heppdt.py, ilcsoft/java.py, ilcsoft/lcio.py, ilcsoft/mysql.py, ilcsoft/ninja.py, ilcsoft/raida.py, ilcsoft/xercesc.py
This a fix proposal for  #12 
- Fixe inconsistent init_ilcsoft.sh files
=> Fix environment issue #12

ilcsoft/ilcsoft.py
Same as #27 but this is to remove DNDEBUG from the actual installation 
- Remove DNDEBUG from default flags for RELWITHDEBINFO
=> Remove DNDEBUG from ilcsoft installation if RELWITHDEBINFO

ilcsoft/baseilc.py
- ilcsoft-install: Allow specifying git branch ` pkg.download.branch = "mybranch"` if `version == [HEAD|dev|devel|master]`
- baseilc: replace tabs with spaces
=> Git branch

ilcsoft/lcfivertex.py
- lcfivertex: adapt to ilcsoft/LCFIVertex#4 splitting LCFIVertex processors in their own library
=> LCFIVertex: change for splitting of processors into their own library

ilcsoft/pandoranew.py
- Added PANDORA_ANALYSIS_DIR env var
- Set LD_LIBRARY_PATH and PATH accordingly
=> PandoraAnalysis environment vars filled

releases/v01-19/release-versions.py
- update v01-19-0X to geant4 10.03.p02 and LCTuple v01-09
=> update to geant4 10.03.p02 and LCTuple v01-09

builds/release-ilcsoft.cfg, examples/macbookfg/release-ilcsoft.cfg, nightly_builds/sl6-c++11_nb_debug.cfg, nightly_builds/sl6-nb_debug.cfg, releases/HEAD/release-ilcsoft.cfg, releases/v01-19/release-ilcsoft.cfg
- DDMarlinPandora will depend on MarlinTrk after merge https://github.com/iLCSoft/DDMarlinPandora/pull/12
- Update all the ilcsoft.cfg by adding DDMarlinPandora dependency with MarlinTrk.
=>  Fix nightly build by updating DDMarlinPandora dependency.

examples/macbookfg/release-ilcsoft.cfg, examples/macbookfg/release-versions.py, releases/v01-19/release-ilcsoft.cfg, releases/v01-19/release-versions.py
- add package FCalClusterer to v01-19 release series and macbookfg example
=> add FCalClusterer to v01-19 and macbookfg

doc/release_notes_ilcsoft_v01-19-05.md, releases/v01-19/release-versions.py
=> prepare v01-19-05-pre

nightly_builds/sl6-c++11_nb_debug.cfg, nightly_builds/sl6-nb_debug.cfg, nightly_builds/ubuntu12.04-nb_debug.cfg, nightly_builds/ubuntu14.04-nb_debug.cfg, releases/HEAD/release-ilcsoft.cfg, releases/v01-19/release-ilcsoft.cfg
- download LCFIPlus from lcfiplus GitHub repository
=> move back to lcfiplus GitHub repo

doc/release_notes_ilcsoft_v01-19-05.md, releases/v01-19/release-versions.py
- v01-19-05(pre07), update Marlin to  v01-15-02 and lcgeo v00-15-03
=> - v01-19-05(pre07), update Marlin and lcgeo

ilcsoft-install, releases/HEAD/release-versions-HEAD.py
- add default path x86_64_gcc54_ub1604 
- update versions of externals for HEAD installs (as in v01-19-05)
=> Add ub1604

builds/release-ilcsoft.cfg, builds/release-ilcsoft7.cfg, releases/HEAD/release-ilcsoft.cfg, releases/v01-19/release-ilcsoft.cfg
Resolves iLCSoft/Garlic#3
- Move Garlic from SVN to GitHub
=> Move Garlic from SVN to GitHub

nightly_builds/nbuild
- added Remi into the nightly build mailing list.
- to receive the nightly build results report. 
=> added Remi into the nightly build mailing list.

releases/HEAD/release-base.cfg, releases/HEAD/release-versions-HEAD.py, releases/v02-00/release-base.cfg, releases/v02-00/release-versions.py
-  update FastJet/contrib to 3.2.1/1.025
- ( was 3.2.0/1.-17)
=>  update FastJet/contrib to 3.2.1/1.025

doc/release_notes_ilcsoft_v02-00-01.md, releases/v02-00/release-versions.py
- update versions and release notes for v02-00-01
=> update versions and release notes for v02-00-01

ilcsoft/xercesc.py
- Overhauled Xerces C installation to point on apache github
fixes #58
=> Xerces C installation

releases/HEAD/release-versions-HEAD.py, releases/v02-00/release-versions.py
- Fixed MySQL path location using platform information
=> Fixed MySQL path location

releases/HEAD/release-versions-HEAD.py, releases/v02-00/release-versions.py
- Use greater or equal instead of greater to set MySQL_path
=> Fix MySQL path. Round 2

ilcsoft/__init__.py, ilcsoft/sio.py, releases/HEAD/release-base.cfg, releases/HEAD/release-ilcsoft.cfg, releases/HEAD/release-versions-HEAD.py
- Added new module SIO
- Added SIO installation (v00-00-02) in base software only for HEAD for the moment
=> New SIO module

ilcsoft/eigen.py, releases/HEAD/release-base.cfg, releases/HEAD/release-ilcsoft.cfg, releases/HEAD/release-versions-HEAD.py
- Eigen module now downloads and installs Eigen from sources
- HEAD version scripts now download and install Eigen from sources
- Eigen version set to 3.3.7
=> New Eigen module

ilcsoft/baseilc.py, ilcsoft/bbq.py, ilcsoft/boost.py, ilcsoft/clhep.py, ilcsoft/dd4hep.py, ilcsoft/dd4hep_examples.py, ilcsoft/eigen.py, ilcsoft/fastjet.py, ilcsoft/geant4.py, ilcsoft/gsl.py, ilcsoft/ilcsoft.py, ilcsoft/lcgeo.py, ilcsoft/marlinpkg.py, ilcsoft/mysql.py, ilcsoft/qt5.py, ilcsoft/root.py, ilcsoft/xercesc.py, releases/HEAD/release-base.cfg, releases/HEAD/release-ilcsoft.cfg, releases/HEAD/release-versions-HEAD.py, releases/v02-01/release-base.cfg, releases/v02-01/release-ilcsoft.cfg, releases/v02-01/release-versions.py, scripts/use_gcc82_cvmfs.sh
- Switched ON C++ 17 flag
- Pass correctly cxx/c standard to following packages:
- Boost (b2 args)
- GSL: Passing c11 standard (latest for C)
- Fastjet: via configure command (using CXXFLAGS)
- Fastjet: set flag `--enable-auto-ptr=no` to be compatible with c++17
- Added function to add a CMake cache variable per module using `addCMakeCache()`
- Corrected all paths to CMake config files to be exported in ILCSoft.cmake
Note:
- `CondDBMySQL` needed an upgrade. See: https://github.com/iLCSoft/CondDBMySQL/pull/3 
- `KiTrackMarlin` needed an upgrade. See: https://github.com/iLCSoft/KiTrackMarlin/pull/5
- `ForwardTracking` needed an upgrade. See: https://github.com/iLCSoft/ForwardTracking/pull/10
TODO: 
Fixes https://github.com/iLCSoft/iLCInstall/issues/76
=> [WIP] C++ 17 upgrade

builds/release-ilcsoft7.cfg
- Fix additional comma in release-ilcsoft7.cfg for nightly builds
=> Nightly build fix, round 4

releases/v02-01/release-versions.py
- v02-01 versions file:
- Set LCFIPlus version to v00-09
=> LCFIPlus v00-09

releases/v02-01/release-versions.py
- Set packages version:
- lcgeo: `v00-16-06`
- DD4hep: `v01-11-01`
=> v02-01 final version

doc/release_notes_ilcsoft_v02-01.md
- Final release notes edition for iLCSoft 02-01 release
=> Release v02-01

ilcsoft/gbl.py
=> Use new GBL repo at GitHub

ilcsoft/gbl.py
=> Fix bug in dependency

builds/release-ilcsoft-lcg.cfg, builds/release-ilcsoft.cfg, builds/release-ilcsoft7.cfg
- Fixed SIO configuration for nightly builds
=> Nightly builds: SIO config

.travis-ci.d/requirements.txt
- Fix for the CI, increment pytest version requirement
=> CI: upgrade pytest requirements

scripts/tagging/gitinterface.py
- ilcsofttagger: Fix first release tagging script
=> fix first release tagging

doc/release_notes_ilcsoft_v02-01-01.md, releases/v02-01/release-versions.py
- Upgraded versions for new release v02-01-01
=> V02-01-01 tagging

doc/release_notes_ilcsoft_v02-01-02.md, releases/v02-01/release-versions.py
- Updated packages version:
- Marlin to v01-17-01
- LCIO to v02-14-02
- Added release notes
=> Release v02-01-02

doc/release_notes_ilcsoft_v02-02.md, releases/v02-02/release-versions.py
- Upgraded MarlinReco version. 
- Updated release notes for v02-02
=> Final version v02-02

docker/cvmfs-install/Dockerfile.cvmfs-install.centos7, docker/cvmfs-install/Readme.md
- Added Dockerfile for CVMFS installation on centos7. 
- Added complete Readme file with corresponding installation procedure
=> Dockerfile for cvmfs installation

docker/cvmfs-install/Dockerfile.cvmfs-install.centos7
- Add a few more packages in order to start installing things with spack inside the cvmfs installation container.
=> Add a few packages to be able to install things with spack

docker/cvmfs-install/Readme.md
- fix cvmfs readme wrt. using singularity
- using a dedicated home_dir on startup
=> fix cvmfs readme wrt. using singularity

examples/macbookfg/release-base.cfg, examples/macbookfg/release-ilcsoft.cfg, examples/macbookfg/release-versions.py, ilcsoft/__init__.py, ilcsoft/edm4hep.py, ilcsoft/podio.py
- add edm4hep and podio install scripts
- update macbook example
- add edm4hep and podio
- updated to Catalina (10.15.7)
=> Add edm4hep

scripts/tagging/parseversion.py, scripts/tests/Test_Tagging.py
- Add support for "." version delimiter
=> Add support for . version delimiter

doc/release_notes_ilcsoft_v02-02-02.md, releases/v02-02/release-versions.py
- Update ILDPerformance to v01-10
- Update MarlinUtil to v01-16
- Update MarlinReco to v01-31
=> New patch release v02-02-02

ilcsoft/boost.py, ilcsoft/eigen.py, ilcsoft/geant4.py, releases/HEAD/release-base.cfg, releases/HEAD/release-ilcsoft.cfg, releases/HEAD/release-versions-HEAD.py
- update versions in HEAD release scripts:
- geant4 11.0 root 6.24.06,...
- 
=> New head vers

releases/HEAD/release-ilcsoft.cfg, releases/HEAD/release-versions-HEAD.py
- add EDM4hep and PODIO to HEAD releases
=> add EDM4hep and PODIO to HEAD releases

releases/v02-03/release-ilcsoft.cfg, releases/v02-03/release-versions.py
- Remove ILDConfig from installed packages again as it is installed separately in any case.
=> Remove ILDConfig from installed packages for v02-03 series

doc/release_notes_ilcsoft_v02-03-01.md, releases/HEAD/release-ilcsoft.cfg, releases/v02-03/release-ilcsoft.cfg, releases/v02-03/release-versions.py
- Include latest version of packages
- LCIO v02-19
- Marlin v01-19
- ILCUtil v01-07
- MarlinTrkProcessors v02-12-02
- KiTrackMarlin v01-13-02
- MarlinUtil v01-17
- MarlinDD4hep v00-06-02
- MarlinReco v01-33-01
- ILDPerformance v01-11
- lcgeo v00-18
- podio v00-16-01
- EDM4hep v00-07-02
=> v02-03-01 patch release to v02-03 developers release series

ilcsoft/__init__.py, ilcsoft/k4edm4hep2lcioconv.py, releases/HEAD/release-ilcsoft.cfg, releases/HEAD/release-versions-HEAD.py
- Add the `k4EDM4hep2LcioConv` package
- Bump a few external versions in the HEAD releases
=> Add k4EDM4hep2LcioConv package

releases/v02-03/release-versions.py
- Bump the podio version to v00-16-06 to include some important bug fixes
=> Bump podio version to v00-16-06
