iLCSoft/iLCInstall

builds/release-versions-HEAD.py
ilcsoft/fastjet.py
nightly_builds/release-versions.py
nightly_builds/sl5_64bit-nb_debug.cfg
nightly_builds/sl6-c++11_nb_debug.cfg
nightly_builds/sl6-nb_debug.cfg
nightly_builds/ubuntu14.04-nb_debug.cfg
releases/HEAD/release-ilcsoft.cfg
releases/HEAD/release-versions-HEAD.py
releases/v01-19/release-ilcsoft.cfg
releases/v01-19/release-versions.py

in order to rename the FastJetClustering repo to `obsolete_FastJetClustering` and not break the nightly builds or new installations of last release.
* removed from nightly builds
* changed location in ilcsoft/fastjet.py module for installation of existing tags
When this PR is merged I will rename the repository
- Removed FastJetClustering from installed packages, because the processor was merged into the MarlinFastJet package

Prepare for renaming of FastJetClustering package

---

scripts/ilcsofttagger.py
scripts/tagging/gitinterface.py
scripts/tagging/helperfunctions.py
scripts/tagging/parseversion.py

needs python 2.7
runs from the scripts folder (unless you export path and pythonpath to point to the right places)
GitTokens.py needs to be in a folder in the PYTHONPATH
usage:
ilcsofttagger --packages lcgeo marlin aidasoft/dd4hep fcalsw/fcalclusterer ... [--properRelease] [--makeTags] [--file packageFile]
* default is dry run mode use --makeTags to actually make the releases
* default is pre-release tags, use --properRelease to make real release
* The script will parse github pull requests to collate release notes
and write them into doc/ReleaseNotes.md
* The script will update the _VERSION_MAJOR, MINOR, PATH in the base
CMakeLists.txt file to the new version
* One needs a github personal access token in a file called
GitTokens.py in a constant called GITHUBTOKEN, see helperfunctions
for …

Add ilcsofttagging script to create releases for github packages

---

builds/release-ilcsoft.cfg
releases/HEAD/release-ilcsoft.cfg
releases/v01-19/release-ilcsoft.cfg

- Follow the GBL update, to add option "GBL_EIGEN_SUPPORT_ROOT" in aidaTT.
- GBLInterface.cc still using ROOT for this moment.

Added '-DGBL_EIGEN_SUPPORT_ROOT' to 'CMAKE_CXX_FLAGS' for aidaTT.

---

scripts/tagging/gitinterface.py

ensure latestTagInfo is filled before, e.g., isUpToDate is called

Tagging: Fill last tag info in Repo constructor, fixes #18

---

scripts/tagging/gitinterface.py

Give the tag the same name as the release

Tagging: use correct (pre)-tag name when making release, fixes #21

---

.coveragerc
.travis-ci.d/requirements.txt
.travis-ci.d/run-unittests.sh
.travis-ci.d/set-reportstyle.sh
.travis.yml
README.md
pytest.ini
scripts/ilcsofttagger.py
scripts/tagging/gitinterface.py
scripts/tagging/helperfunctions.py
scripts/tests/Test_Tagging.py

- Added tests for large parts of the ilcsoft tagger files
- Prevent the printout of the githubtoken in DEBUG mode
- Prevent creation of tags that are older than the last tag (e.g., 2.8-pre if 2.8 was created already)
- Fix a bug in the error reporting of packages causing exception for using variable before it is assigned
- add --lastTag option to set the tag to use instead of finding the last tag automatically. Only works if a single package is specified

Tagging Improvements, Tests

---

scripts/tagging/gitinterface.py

Together with aidasoft/dd4hep#151 this allows tagging of dd4hep without manual intervention...
- Tagging: enable complete tagging of dd4hep, also changing DDSegmentation version
- Tagging: fix bug when trying to tag a branch that is not master. the CMakeLists file was still taken from the master branch.

Tagging4 dd4hep

---

ilcsoft/ilcsoft.py

Since [this change](https://gitlab.kitware.com/cmake/cmake/commit/0ddfc51f6a68c61d84b5b4818b32ecbf755a949a) in CMake the default value for `RELWITHDEBINFO` has `DNDEBUG` added this suppresses all the debug output from streamlog when using default compilation. I think streamlog Debug output should only be suppressed in `Release`
- Remove `-DNDEBUG` from the CMake default for `RELWITHDEBINFO`
- Remove cmake commands from the `ILCSoft.cmake.env.sh`

Force old default value for RELWITHDEBINFO

---

builds/release-ilcsoft.cfg

- Use LCFIPlus from Github/LCFIPlus instead of lcfiplus/LCFIPlus in nightly

Use LCFIPlus from Github/LCFIPlus instead of lcfiplus/LCFIPlus in nightly

---

ilcsoft/ilcutil.py

- Changed ilcutil.py module to get its sources from Github instead of desy svn as default

Set Github as download source as default for ilcutil instead of svn

---

builds/release-versions-HEAD.py
examples/lcfiplus/release-versions.py
examples/macbookfg/release-versions.py
nightly_builds/release-versions.py
releases/HEAD/release-versions-HEAD.py
releases/v01-19/release-versions.py
releases/v01-19/tagging_v01-19.py

- Updated Overlay version to v00-20.
- which tag needed by ILDConfig/StandardConfig/production

Updated Overlay version to v00-20.

---

ilcsoft/baseilc.py
ilcsoft/cernlib.py

- Changed urllib to urllib2 import to improve certificate check on url open

urllib to urllib2

---

scripts/tagging/gitinterface.py
scripts/tagging/helperfunctions.py
scripts/tests/Test_Tagging.py

- ILCSoftTagging: Implement access to github API via requests module, fixes #48.
* needs the `requests` module installed, automatic fall back to curl based calls if not present

Use requests

---

releases/HEAD/release-ilcsoft.cfg

- Enable building the doc for MarlinTPC in the nightly builds and HEAD releases.
- Oliver has fixed building the documentation for MarlinTPC.

 Enable building the doc for MarlinTPC in the nightly builds and HEAD releases.

---

ilcsoft/clhep.py
releases/v02-00/release-versions.py

- CLHEP package: updated tarball location
- Xerces-C package: fixed versioning scheme. Updated version to 3.2.2

Fix CLHEP and Xerces packages

---

ilcsoft-install
releases/HEAD/release-versions-HEAD.py
releases/v02-00/release-versions.py

- Added cmd line option `--install-prefix` to `ilcsoft-install` script, to specify install prefix without modifying the scripts manually
- Updated 'version.py' scripts accordingly in `releases` directory

Added install prefix command line option 

---

ilcsoft/xercesc.py

- Fixed possible location of xerces lib during installation process (lib64)

XercesC library location (lib64)

---

builds/release-ilcsoft.cfg
builds/release-ilcsoft7.cfg
builds/release-versions-HEAD.py
ilcsoft/dd4hep.py

- dd4hep: add boost library path to post install LD_LIBRARY_PATH
- nightlies: drop explicit use of c++11

dd4hep with boost, nightly tweaks

---

ilcsoft/ilcsoft.py

- export CMAKE_CXX_STANDARD to ILCSoft.cmake if it was set at compile time of the release

ILCSoft: export CMAKE_CXX_STANDARD to ILCSoft.cmake

---

ilcsoft/boost.py
releases/HEAD/release-base.cfg
releases/HEAD/release-ilcsoft.cfg
releases/HEAD/release-versions-HEAD.py

- Change Boost module to download and compile Boost like any other package
- Set Boost version to 1.65.0
- Added Boost module to list packages to install (base) and link (ilcsoft). Only for HEAD version

Boost module compilation

---

ilcsoft/lcfivertex.py
releases/HEAD/release-ilcsoft.cfg
releases/HEAD/release-versions-HEAD.py

- Removed references to Boost_path in HEAD scripts
- Fixed LCFIVertex Boost dependency
- Removed CMake var for BOOST_ROOT as CMake can find BOOST using the env variable BOOST_ROOT instead. Done for DD4hep and LCFIVertex

Fix boost install

---

ilcsoft/dd4hep.py

- set `PYTHONPATH` for DD4hep to `$DD4HEP/lib/pythonX.Y/site-packages:$DD4HEP/python` to align with AIDASoft/DD4hep#572 

Add new location of DD4hep python packages

---

.gitignore
ilcsoft-install
ilcsoft/aidaTT.py
ilcsoft/baseilc.py
ilcsoft/ced.py
ilcsoft/dd4hep.py
ilcsoft/dd4hep_examples.py
ilcsoft/geant4.py
ilcsoft/ilcsoft.py
ilcsoft/lccd.py
ilcsoft/lcgeo.py
ilcsoft/marlin.py
ilcsoft/mysql.py
ilcsoft/pandoranew.py
ilcsoft/qt5.py
ilcsoft/root.py
releases/HEAD/release-base.cfg
releases/HEAD/release-ilcsoft.cfg
releases/HEAD/release-versions-HEAD.py
releases/v02-01/release-base.cfg
releases/v02-01/release-ilcsoft.cfg
releases/v02-01/release-versions.py
scripts/use_gcc82_cvmfs.sh

- Missing CMake dependency for ROOT package
- Fixed CMake python install script to handle version higher than 3.9
- Added new package module for `Qt5`. Meant to replace `QT` (Qt4) module
- Added proper Boost package that compiles it (no link).
- Added proper Eigen3 package installation with download and install 
- Set `MARLIN_GUI` to OFF as of now it is not compatible with Qt5
- Added -std=c++${CXX_STANDARD} to PandoraPFANew as a workaround to select the CXX_STANDARD. See https://github.com/PandoraPFA/PandoraPFA/pull/4
- Upgraded software versions:
- `ROOT` to `6.18.04`. Versions < `6.16.00` are broken due to XROOT internal download which points on a wrong tarball location.
- `DD4hep` and `DD4hepExamples` to `v01-11`
- `Geant4` to `10.4.p03`
- `CMake` to `3.15.5`
- `Qt` …

[WIP] Bug fixes and major versions upgrades

---

ilcsoft/geant4.py
ilcsoft/ilcsoft.py

- Fixed export of `cmakeconfig` in shell script
- Fixed additional whitespace in geant4 `cmakeconfig` variable
Fixes #80

Fix usage of cmakeconfig variable

---

builds/release-ilcsoft.cfg
ilcsoft/baseilc.py
ilcsoft/clhep.py
ilcsoft/geant4.py

- fix CLICdp nightly builds
- after #78 the nightly builds for CLICdp were broken due to non-standard path naming conventions ( having the machine/compiler as lowest directory rather than the version)
- this is fixed by allowing to set the `version` as extra parameter for geant4 and clhep
- these packages need the correct version for specifying the path to the CMakeConfig script
- should fix #80 

Fix clicdp nightlies

---

ilcsoft/kaltest.py
ilcsoft/marlinpkg.py

- Fixed missing build_env.sh sourcing before configure in packages `kaltest` and `marlinpkg`

Missing build_env.sh sourcing

---

ilcsoft/bbq.py
ilcsoft/ddkaltest.py
ilcsoft/gbl.py
ilcsoft/kaltest.py
ilcsoft/kitrack.py
ilcsoft/marlintrk.py
ilcsoft/pathfinder.py
ilcsoft/raida.py

- Added missing source of build_env.sh before running CMake command in various packages:
- BBQ, DDKalTest, GBL, KalTest, KiTrack, KiTrackMarlin, MarlinTrk, pathfinder, RAIDA
Fixes #80

Missing build_env.sh source. Second round

---

ilcsoft/ilcsoft.py

- Fix export of compiler setup:
- source setup.sh from compiler path (for example from CVMFS) in init_ilcsoft.sh
- if setup.sh not found (for example default compiler in /usr/bin) just export PATH and LD_LIBRARY_PATH as before.
Fixes #82

Fix setup of compiler in init_ilcsoft.sh

---

builds/release-ilcsoft.cfg

- Missing CMake support switch in nightly build config. Packages affected:
- MarlinKinfit, FCalClusterer, Clupatra
Fixes #80

Missing CMake support switch in nightly build config

---

builds/release-ilcsoft7.cfg

- Missing CMake support switch in nightly build config for gcc7. Packages affected:
- MarlinKinfit, FCalClusterer, Clupatra

Fix nightly build for gcc7 config

---

builds/release-ilcsoft7.cfg

- Same fixes as in #84 but for `release-ilcsoft7.cfg`
- Missing fix of Geant4 and CLHEP version not set

Nightly build fix, round 3

---

releases/HEAD/release-versions-HEAD.py

- Fixed base software versions in the HEAD scripts
- CED changed to v01-09-03
- ILCUTIL changed to v01-06

Fixed HEAD versioning

---

releases/HEAD/release-versions-HEAD.py
releases/v02-01/release-versions.py

- Fixed XercesC version tag name. Use the same version `v3.2.2`
Fixes #95

Xerces tag fix

---

ilcsoft/root.py

- Fixed compilation of mathmore depending on whether ROOT can find GSL or not:
+ Set to OFF gsl builtin compilation.
+ Provide path to GSL ROOT location, pointing to the one installed in iLCSoft

Fixed ROOT mathmore compilation 

---

releases/HEAD/release-ilcsoft.cfg
releases/v02-01/release-ilcsoft.cfg
releases/v02-01/release-versions.py

- Include MarlinTPC software again in the iLCSoft stack
- Set MarlinTPC version to `v01-06`

MarlinTPC is back

---

releases/v02-01/release-versions.py

- update DD4hep version to v01-11-02 for ilcsoft release v02-01

update DD4hep version to v01-11-02

---

releases/HEAD/release-base.cfg
releases/v02-01/release-base.cfg

- increase timeout to prevent installation failures due to slow G4 data downloads (default is 1500 s)

increase timeout for g4 data download

---

builds/release-ilcsoft-lcg.cfg
builds/release-ilcsoft.cfg
builds/release-ilcsoft7.cfg
builds/release-versions-HEAD.py
builds/release-versions-HEAD7.py
builds/release-versions-lcg.py

- add standalone SIO library to LCG releases and nightlies
- will be needed for LCIO and PODIO

add SIO library to LCG releases and nightlies

---

ilcsoft/geant4.py

- Fixed Geant4 sources location
- Moved from `geant4.cern.ch/support/source` to `cern.ch/geant4-data/releases`

Fixed Geant4 sources location

---

doc/release_notes_ilcsoft_v02-02.md
releases/v02-02/release-versions.py

- Upgraded iLCUtil to v01-06-01 (find mysql fix for ubuntu). 
- Updated v02-02 release notes

Upgraded iLCUtil version

---

docker/cvmfs-install/Dockerfile.cvmfs-install.centos7

- Add proper cvmfs repository for installing cvmfs in Docker image
Without this yum will not be able to install cmvfs because it will not
be available

Add proper cvmfs repo to be able to install it

---

.gitignore
doc/release_notes_ilcsoft_v02-02-01.md
releases/v02-02/release-versions.py

- Upgrade MarlinReco to v01-29
- Upgrade ILDPerformance to v01-09
- Upgrade SIO to v00-01
- Upgrade LCIO to v02-16-01

Prepare release v02-02-01

---

doc/release_notes_ilcsoft_v02-02-01.md
releases/v02-02/release-versions.py

- Upgrade Overlay to v00-22-02
To be included still in the v02-02-01 release

Include fixes for Overlay package into release 02-02-01

---

ilcsoft/sio.py

- Make sure that `libsio` is found after CMake updates to sio
iLCSoft/SIO/#15 introduced a small change to where `libsio` will be installed. This makes sure that the install script still recognizes this as a successful install.

Update install paths for libsio

---

doc/release_notes_ilcsoft_v02-02-01.md
releases/v02-02/release-versions.py

- Update MarlineReco version to v01-30
To still include the updated calo digitization in the v02-02-01 release.

Bump MarlinReco version once more before release

---

docker/cvmfs-install/Dockerfile.cvmfs-install.centos7

- Update cvmfs installation docker container 
Removing the explicit installation of cvmfs inside the container, since we do not need it because we bind-mount the necessary repositories. Having cvmfs installed inside the image can lead to problems when starting the image, depending on how singularity is configured:
```
FATAL:   container creation failed: mount /proc/self/fd/10->/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/10: failed to mount squashfs filesystem: input/output error
```
Also cleaning up after installing to reduce the size of the image.

Update Dockerfile for producing the cvmfs-install container image

---

scripts/ilcsofttagger.py
scripts/tagging/gitinterface.py
scripts/tagging/helperfunctions.py
scripts/tagging/parseversion.py
scripts/tests/Test_Tagging.py

I think this works. cf. https://github.com/iLCSoft/CLICPerformance/releases/tag/v02-04-01
Related to #132 
- ilcsofttagger: make python3 compatible, keep python2 compatibility for the moment
- ilcsofttagger: add --ignoreMissingCmake flag to ignore the absence of CMakeLists.txt in the repository
- ilcsofttagger: no longer look up release notes in comments to PRs, only the opening post
- ilcsofttagger: try to get author name from the first commit of a PR not the last, might fix issue with wrongly attributed changes in the release notes

Py3 tagger

---

doc/release_notes_ilcsoft_v02-02-03.md
ilcsoft/lcio.py
releases/v02-02/release-versions.py

- Update LCIO to v02-17
- Update MarlinReco to v01-32
- Update MarlinTrk to v02-09
- Update MarlinUtil to v01-16-01
- Update CEDViewer to v01-19
- Update LCTuple to v01-13
- Update ConformalTracking to v01-11
- Update MarlinTrkProcessors to v02-12
- Update Overlay to v00-22-03
- Update DDMarlinPandora to v00-12
- Update iLCUtil to v01-06-02
- Update lcgeo to v00-16-07
- Update LCFIPlus to v00-10-01

New v02-02-03 patch release

---

ilcsoft-install
ilcsoft/boost.py

- add support for (central) ubuntu installations w/ 20.04
- update download path for boost

add support for ubuntu 20.04

---

doc/release_notes_ilcsoft_v02-03.md
ilcsoft-install
releases/v02-03/release-base.cfg
releases/v02-03/release-ilcsoft.cfg
releases/v02-03/release-versions.py

- Major upgrades to external software, most importantly **switching from python2 to python3**, and to newer version of gcc.
- Update all external software to latest available versions
- Include latest versions of iLCSoft packages
- CED v01-09-04
- MarlinFastJet v00-05-03
- MarlinReco v01-33
- lcgeo v00-16-08
- CEDViewer v01-19-01
- KalTest v02-05-01
- DDKalTest v01-07
- LCIO v02-17-01
- MarlinKinfitProcessors v00-05
- LCCD v01-05-01 
- GEAR v01-09-01 
- MarlinDD4hep v00-06-01 
- MarlinUtil v01-16-02 
- MarlinTrk v02-09-01 
- MarlinTrkProcessors v02-12-01 
- MarlinKinfit v00-06-01 
- Overlay v00-22-04 
- KiTrackMarlin v01-13-01 
- ForwardTracking v01-14-01 
- LCTuple v01-14
- ILDConfig v02-03
- Physsim v00-04-02

Preparations for a new developers release cycle v02-03

---

.github/workflows/python_unittests.yml
ilcsoft/cernlib.py
ilcsoft/ilcsoft.py
ilcsoft/ninja.py
ilcsoft/test_version.py
releases/HEAD/release-ilcsoft.cfg
releases/v02-03/release-ilcsoft.cfg
scripts/tagging/parseversion.py
scripts/tests/Test_Tagging.py

DESY SVN server has been decomissioned and some test beam packages have not yet been migrated to gitlab repositories. For now, disabling these packages for HEAD and v02-03 releases.
- Disable `PathFinder`, `MarlinTPC`, and `BBQ` packages from being installed by default for, as they are no longer available from the DESY SVN server and have not yet been fully migrated to the DESY gitlab server.
- Fix tests to work with latest versions of `pytest`. The main reason is that starting with pytest 7.2.0(?) py.test.raises only works if py is also installed. Given https://github.com/pytest-dev/py/issues/288 it is probably easiest to just use pytest directly if possible.
- Fix a few escape sequence warnings in packages.

Disable packages living on decomissioned svn server

---

ilcsoft/__init__.py
ilcsoft/marlinpkg.py
ilcsoft/physsim.py
releases/HEAD/release-ilcsoft.cfg
releases/v02-03/release-ilcsoft.cfg

- Make `Physsim` its own package to accomodate more easily for changed behavior after CMake config updates in iLCSoft/Physsim#2
- Make `MarlinPKG` slightly more clever for discovering libraries that need to be put on `MARLIN_DLL`

Make physsim work with updated CMake config

---

ilcsoft/geant4.py

- Make sure that `CMAKE_PREFIX_PATH` points to the right place for Geant4 > v11.1 where it has been moved to a more standard location.

Fix CMAKE_PREFIX_PATH for Geant4 > v11.1

---

doc/release_notes_ilcsoft_v02-03-02.md
ilcsoft/k4edm4hep2lcioconv.py
releases/HEAD/release-ilcsoft.cfg
releases/v02-03/release-ilcsoft.cfg
releases/v02-03/release-versions.py

- Add new package
- k4EDM4hep2LcioConv v00-05 (LCIO to EDM4hep conversion)
- Update base package versions
- DD4hep 01-25-01
- ROOT 6.28/04
- Geant4 11.1.1
- Update package versions to latest tags
- MarlinReco v01-34
- podio v00-16-05
- EDM4hep v00-10
- iLCUtil v01-07-01
- LCIO v02-20
- lcgeo (k4geo) v00-18-01
- MarlinUtil v01-17-01
- RAIDA v01-10
- ConformalTracking v01-11-01
- MarlinTrkProcessors v02-12-03
- Overlay v00-23
- ILDPerformance v01-12

Prepare v02-03-02 patch release

---

.github/workflows/python_unittests.yml

- Remove workflow that requires a no longer supported python version. Fixes #167 

Remove unittests running on python 2.7

---

ilcsoft/podio.py

- Make sure to put `PATH` and `ROOT_INCLUDE_PATH` into the environment for podio.

Add more environment paths for podio

---

ilcsoft/baseilc.py

- add ROOT_INCLUDE_PATH to base module
- needed for podio.py (see: https://github.com/iLCSoft/iLCInstall/pull/168)

add ROOT_INCLUDE_PATH to base module

---

examples/macbookfg/release-versions.py
ilcsoft/baseilc.py
ilcsoft/ilcsoft.py
ilcsoft/marlinpkg.py

- some fixes to keep up w/ changes in key4hep packages
-  allow HEAD branch to be called main
- patch lcgeo install to work w/ latest k4geo
- Allow Marlin packages to be installed into `lib64` or `lib` and make sure that `MARLIN_DLL` is populated properly.
- update versions of externals in example macbookfg

Some updates for key4hep and Marlin packages
